name: ci

on:
  pull_request:
  push:
    branches:
      - main
      - develop
      - feature/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore ./src/UpskillTracker/UpskillTracker.csproj

      - name: Build
        run: dotnet build ./src/UpskillTracker/UpskillTracker.csproj --configuration Release --no-restore
